<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
    { "@context" : "http://schema.org",
    "@type" : "LocalBusiness",
    "name" : "Taylor Properties",
    "image" : "{{ asset('images/logos/TaylorProperties-horizontal-fullcolor.png') }}",
    "telephone" : "800-590-0925",
    "address" : { "@type" : "PostalAddress", "streetAddress" : "175 Admiral Cochrane Drive, Suite 112", "addressLocality" : "Annapolis", "addressRegion" : "MD", "postalCode" : "21401" },
    "openingHoursSpecification" : { "@type" : "OpeningHoursSpecification", "dayOfWeek" : { "@type" : "DayOfWeek", "name"
    : "Monday - Friday" } },
    "url" : "www.taylorproperties.co" }
</script>